name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Pin site to IPFS via Pinata
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
      run: |
        # Crée un fichier temporaire pour le contenu du site
        mkdir -p ./site
        cp -r * ./site

        # Envoie les fichiers à Pinata sous forme de dossier
        response=$(curl -X POST https://api.pinata.cloud/pinning/pinFileToIPFS \
          -H "pinata_api_key: $PINATA_API_KEY" \
          -H "pinata_secret_api_key: $PINATA_API_SECRET" \
          -F "file=@site" \
          -F "pinataOptions={\"wrapWithDirectory\": true}")

        # Récupère le CID du site
        cid=$(echo $response | jq -r '.IpfsHash')

        # Affiche le lien public pour accéder au site
        echo "Le site est maintenant en ligne sur : https://gateway.pinata.cloud/ipfs/$cid"
