name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Pin site to IPFS via Pinata
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
      run: |
        zip -r site.zip .
        
        # Upload du fichier sur Pinata
        response=$(curl -X POST https://api.pinata.cloud/pinning/pinFileToIPFS \
          -H "pinata_api_key: $PINATA_API_KEY" \
          -H "pinata_secret_api_key: $PINATA_API_SECRET" \
          -F "file=@site.zip")
        
        cid=$(echo $response | jq -r '.IpfsHash')
        echo "Le site est maintenant en ligne sur : https://gateway.pinata.cloud/ipfs/$cid"
